baseURL = "https://jaejin0me.github.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "Jaejin's blog"
enableRobotsTXT = true
enableEmoji = true
theme = "even"
publishDir = "docs"

hasCJKLanguage = true     # has chinese/japanese/korean ? # ゅ뒯汝役뗦삸똿訝뻼\ζ뻼\⒵뻼
paginate = 10                                              # 腰뽭〉驪뤻〉양ㅊ꾣뻼塋졿빊
disqusShortname = ""      # disqus_shortname
googleAnalytics = "UA-111561979-1"      # UA-XXXXXXXX-X
copyright = "Jaejin Jang"            # default: author.name        # 容섋訝뷰툔뀓營쉪author.name 

[author]                  # essential                     # 恙낂
  name = "Jaejin Jang"

[sitemap]                 # essential                     # 恙낂
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 띸쉰퐬
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2017"            # Site creation time          # 塋숂궧兩븀쳦띌뿴

  # site info (optional)                                  # 塋숂궧岳→겘竊덂룾됵펽訝띺誤곭쉪빳닸렏力③뇢됵펹
  logoTitle = "Jaejin's blog"        # default: the title value    # 容섋 訝딃씊溫양쉰꼝itle
  keywords = ["Jaejin"]
  description = "Jaejin's blog."

  # paginate of archives, tags and categories             # 壤믤。곫젃嶺얇곩늽映삥캀窈득샑鹽븀쉪뉒쳽곁쎅竊뚦뻠溫엶밥맏訝訝よ푵鸚㎫쉪
  archive-paginate = 18

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 맔양ㅊ耶쀦빊瀯잒訝롩쁾瑥삥뿶
  moreMeta = true

  # 訝雅쎾뀲掠凉놂펽鵝졽튋빳ⓩ캀訝影뉐냵若밭쉪 front matter 訝뭹野밧뜒影뉐냵若밧뀽닑凉윇雅쎾뒣쏙펽archetypes/default.md η쐦닷쩀岳→겘
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 맔凉쎅壤
  autoCollapseToc = false   # Auto expand and collapse toc                              # 퐬ゅ뒯掠뺝/섇룧
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 맔뵪fancybox竊덂쎗뉐룾밧눤竊
  bootcdn = false           # In china. @Deprecated: use [params.publicCDN]             # 맔鵝욜뵪bootcdn(@Deprecated: 瑥룝슴params.publicCDN])
  mathjax = false           # see https://www.mathjax.org/                              # 맔鵝욜뵪mathjax竊덃빊耶뀶凉륅펹
  linkToMarkDown = false    # if you config contentCopyright and hugo output .md files. # 맔③벦ε댆markdown잌쭓뉏뻑竊덂쫩쒍퐷띸쉰雅녵툔®쉪溫멨룾뤺亮뜹뀅溫퇲ugo잍닇markdown뉏뻑竊

  contentCopyright = 'Jaejin Jang'

  changyanAppid = ""        # Changyan app id             # 낁
  changyanAppkey = ""       # Changyan app key
  livereUID = ""            # LiveRe UID                  # ε퓚
  baidu_push = false        # baidu push                  # 얍벧
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification         # 瘟룡춯

  [params.publicCDN]        # load these files from public cdn                          # 뵪у뀻CDN竊뚪よ죱若싦퉱
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'

  [params.busuanzi]         # count web traffic by busuanzi                             # 맔鵝욜뵪訝띹뮏耶먪퍨溫←쳶배뇧
    enable = false
    siteUV = true
    sitePV = true
    pagePV = true

  [params.reward]                                         # 뉒쳽볢탲
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"           # 孃에雅뚨뺨
    alipay = "/path/to/your/alipay-qr-code.png"           # 퍡若앬틠瀯당쟻

  [params.social]                                         # 鹽얌벡얏렏
    a-email = "mailto:jaejin0me@gmail.com"
    d-facebook = "https://ko-kr.facebook.com/people/%EC%9E%A5%EC%9E%AC%EC%A7%84/100005230447628"
    e-linkedin = "https://www.linkedin.com/in/jaejin0me"
    g-github = "https://github.com/jaejin0me"


# 弱녵툔퓳餘들뀓營룚易덃낏듿룾餓δ슴 hugo 잍닇 .md 뉏뻑
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffix = "md"
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
